In [60]:
#imports
import os
import pandas as pd
import numpy as np
import random
random.seed(1)

In [61]:
# from google.colab import files
# uploaded = files.upload()

In [62]:
import io
brfss_2023_dataset = pd.read_csv('diabetes_dataset.csv')
# Dataset is now stored in a Pandas Dataframe

In [63]:
brfss_2023_dataset.shape

(433323, 350)

In [64]:
pd.set_option('display.max_columns', 500)
brfss_2023_dataset.head()

_STATE  FMONTH        IDATE IMONTH   IDAY    IYEAR  DISPCODE  \
0     1.0     1.0  b'03012023'  b'03'  b'01'  b'2023'    1100.0   
1     1.0     1.0  b'01062023'  b'01'  b'06'  b'2023'    1100.0   
2     1.0     1.0  b'03082023'  b'03'  b'08'  b'2023'    1100.0   
3     1.0     1.0  b'03062023'  b'03'  b'06'  b'2023'    1100.0   
4     1.0     1.0  b'01062023'  b'01'  b'06'  b'2023'    1100.0   

           SEQNO          _PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  \
0  b'2023000001'  2.023000e+09       1.0       1.0       NaN       1.0   
1  b'2023000002'  2.023000e+09       1.0       1.0       NaN       1.0   
2  b'2023000003'  2.023000e+09       1.0       1.0       NaN       1.0   
3  b'2023000004'  2.023000e+09       1.0       1.0       NaN       1.0   
4  b'2023000005'  2.023000e+09       1.0       1.0       NaN       1.0   

   CELPHON1  LADULT1  NUMADULT  RESPSLC1  LANDSEX2  LNDSXBRT  SAFETIME  \
0       2.0      1.0       2.0       1.0       2.0       NaN       NaN   
1       2.0      1.0       1.0       NaN       2.0       NaN       NaN   
2       2.0      1.0       1.0       NaN       2.0       NaN       NaN   
3       2.0      1.0       2.0       1.0       2.0       NaN       NaN   
4       2.0      1.0       1.0       NaN       2.0       NaN       NaN   

   CTELNUM1  CELLFON5  CADULT1  CELLSEX2  CELSXBRT  PVTRESD3  CCLGHOUS  \
0       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
1       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
2       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
3       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
4       NaN       NaN      NaN       NaN       NaN       NaN       NaN   

   CSTATE1  LANDLINE  HHADULT  SEXVAR  GENHLTH  PHYSHLTH  MENTHLTH  POORHLTH  \
0      NaN       NaN      NaN     2.0      2.0      88.0      88.0       NaN   
1      NaN       NaN      NaN     2.0      2.0      88.0      88.0       NaN   
2      NaN       NaN      NaN     2.0      4.0       6.0       2.0       1.0   
3      NaN       NaN      NaN     2.0      2.0       2.0      88.0      88.0   
4      NaN       NaN      NaN     2.0      4.0      88.0      88.0       NaN   

   PRIMINS1  PERSDOC3  MEDCOST1  CHECKUP1  EXERANY2  EXRACT12  EXEROFT1  \
0       3.0       1.0       2.0       2.0       2.0       NaN       NaN   
1       3.0       1.0       2.0       2.0       1.0       1.0     106.0   
2       3.0       1.0       1.0       1.0       1.0       1.0     205.0   
3       3.0       1.0       2.0       3.0       1.0       1.0     103.0   
4       3.0       1.0       2.0       1.0       1.0       1.0     102.0   

   EXERHMM1  EXRACT22  EXEROFT2  EXERHMM2  STRENGTH  BPHIGH6  BPMEDS1  \
0       NaN       NaN       NaN       NaN     888.0      1.0      1.0   
1      30.0      88.0       NaN       NaN     888.0      1.0      2.0   
2      15.0      88.0       NaN       NaN     205.0      1.0      1.0   
3      30.0      88.0       NaN       NaN     888.0      3.0      NaN   
4      45.0       8.0     107.0     100.0     888.0      1.0      1.0   

   CHOLCHK3  TOLDHI3  CHOLMED3  CVDINFR4  CVDCRHD4  CVDSTRK3  ASTHMA3  \
0       3.0      2.0       2.0       2.0       2.0       2.0      2.0   
1       2.0      1.0       1.0       2.0       2.0       2.0      2.0   
2       2.0      1.0       1.0       2.0       2.0       2.0      1.0   
3       3.0      2.0       2.0       2.0       2.0       2.0      2.0   
4       2.0      2.0       2.0       2.0       2.0       2.0      2.0   

   ASTHNOW  CHCSCNC1  CHCOCNC1  CHCCOPD3  ADDEPEV3  CHCKDNY2  HAVARTH4  \
0      NaN       2.0       2.0       2.0       2.0       2.0       2.0   
1      NaN       2.0       2.0       2.0       1.0       2.0       1.0   
2      1.0       2.0       2.0       2.0       2.0       2.0       1.0   
3      NaN       1.0       1.0       2.0       1.0       2.0       1.0   
4      NaN       2.0       1.0       2.0       1.0       2.0       1.0   

   DIABETE

In [65]:
brfss_df_columned = brfss_2023_dataset[['LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
                                        'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
                                        'DIABETE4', 'MARITAL', 'EDUCA', 'RENTHOM1', 'CPDEMO1C', 'VETERAN3',
                                        'EMPLOY1', 'CHILDREN', 'INCOME3', 'PREGNANT', 'SMOKE100', 'AVEDRNK3',
                                        'USENOW3', 'ACEDEPRS', 'BIRTHSEX', 'SOFEMALE', 'TRNSGNDR',
                                        'ACEDRINK', 'ACEDRUGS', 'ACEDIVRC', 'QSTLANG', '_URBSTAT', '_HLTHPL1']]


In [66]:
# brfss_df_selected = brfss_df_selected.dropna(subset=['DIABETE4'])
brfss_df_columned['DIABETE4'].value_counts()

DIABETE4
3.0    358706
1.0     59786
4.0     10594
2.0      3253
7.0       683
9.0       296
Name: count, dtype: int64

In [67]:
# DIABETE4
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
# Remove NaN values in the DIABETE4 column
brfss_df_selected_no_nan = brfss_df_columned.dropna(subset=['DIABETE4'])

# Replace DIABETE4 values with ordinal categories
brfss_df_selected_no_nan.loc[:, 'DIABETE4'] = brfss_df_selected_no_nan['DIABETE4'].replace({2: 0, 3: 0, 4: 1, 1: 2})

# Remove rows where DIABETE4 is 7 (Don't know) or 9 (Refused)
brfss_df_labeled = brfss_df_selected_no_nan[~brfss_df_selected_no_nan['DIABETE4'].isin([7, 9])]

# Verify the value counts
print(brfss_df_labeled['DIABETE4'].value_counts())
print(brfss_df_labeled.shape)

# Save the cleaned DataFrame
brfss_df_selected = brfss_df_labeled


DIABETE4
0.0    361959
2.0     59786
1.0     10594
Name: count, dtype: int64
(432339, 33)


In [68]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss_df_selected = brfss_df_selected[brfss_df_selected.LSATISFY != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.LSATISFY != 7]
brfss_df_selected.LSATISFY.unique()

array([ 2.,  1., nan,  3.,  4.])

In [69]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss_df_selected = brfss_df_selected[brfss_df_selected.EMTSUPRT != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.EMTSUPRT != 7]
brfss_df_selected.EMTSUPRT.unique()

array([ 1.,  2.,  4.,  3., nan,  5.])

In [70]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDLONELY != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDLONELY != 7]
brfss_df_selected.SDLONELY.unique()

array([ 5.,  3.,  2.,  4., nan,  1.])

In [71]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHEMPLY != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHEMPLY != 7]
brfss_df_selected.SDHEMPLY.unique()

array([ 2.,  1., nan])

In [72]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss_df_selected = brfss_df_selected[brfss_df_selected.FOODSTMP != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.FOODSTMP != 7]
brfss_df_selected.FOODSTMP.unique()

array([ 2., nan,  1.])

In [73]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHFOOD1 != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHFOOD1 != 7]
brfss_df_selected.SDHFOOD1.unique()

array([ 5.,  4., nan,  3.,  2.,  1.])

In [74]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHBILLS != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHBILLS != 7]
brfss_df_selected.SDHBILLS.unique()

array([ 2.,  1., nan])

In [75]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHUTILS != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHUTILS != 7]
brfss_df_selected.SDHUTILS.unique()

array([ 2.,  1., nan])

In [76]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHTRNSP != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHTRNSP != 7]
brfss_df_selected.SDHTRNSP.unique()

array([ 2.,  1., nan])

In [77]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHSTRE1 != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SDHSTRE1 != 7]
brfss_df_selected.SDHSTRE1.unique()

array([ 5.,  3.,  2.,  4., nan,  1.])

In [78]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.MARITAL != 9]
brfss_df_selected.MARITAL.unique()

array([ 1.,  2.,  3.,  6.,  5.,  4., nan])

In [79]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([ 5.,  4.,  6.,  3.,  2.,  1., nan])

In [80]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.RENTHOM1 != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.RENTHOM1 != 7]
brfss_df_selected.RENTHOM1.unique()

array([ 1.,  2.,  3., nan])

In [81]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.CPDEMO1C != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CPDEMO1C != 7]
brfss_df_selected.CPDEMO1C.unique()

array([ 1.,  8.,  3.,  2.,  4.,  5., nan,  6.])

In [82]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.VETERAN3 != 9]
brfss_df_selected.VETERAN3.unique()

array([ 2.,  1., nan,  7.])

In [83]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.EMPLOY1 != 9]
brfss_df_selected.EMPLOY1.unique()

array([ 7.,  8.,  4.,  1.,  5.,  2., nan,  6.,  3.])

In [84]:
brfss_df_selected['CHILDREN'] = brfss_df_selected['CHILDREN'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CHILDREN != 99]
brfss_df_selected.CHILDREN.unique()

array([ 0.,  1.,  4., nan,  2.,  3.,  6.,  5.,  7.,  9., 10.,  8., 14.,
       81., 20., 18., 17., 12., 26., 11., 43., 16., 30., 31., 22., 13.,
       23., 15., 35., 41.])

In [85]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 99]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 77]
brfss_df_selected.INCOME3.unique()

array([ 2.,  7.,  6.,  9.,  3.,  5.,  1., nan,  8.,  4., 11., 10.])

In [86]:
brfss_df_selected['PREGNANT'] = brfss_df_selected['PREGNANT'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PREGNANT != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PREGNANT != 7]
brfss_df_selected.PREGNANT.unique()

array([nan,  0.,  1.])

In [87]:
#5 SMOKE100
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['SMOKE100'] = brfss_df_selected['SMOKE100'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

array([ 1.,  0., nan])

In [88]:
#5 USENOW3
# Change 3 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['USENOW3'] = brfss_df_selected['USENOW3'].replace({3:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.USENOW3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.USENOW3 != 9]
brfss_df_selected.USENOW3.unique()

array([ 0.,  2.,  1., nan])

In [89]:
brfss_df_selected['AVEDRNK3'] = brfss_df_selected['AVEDRNK3'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.AVEDRNK3 != 99]
brfss_df_selected = brfss_df_selected[brfss_df_selected.AVEDRNK3 != 77]
brfss_df_selected.AVEDRNK3.unique()

array([nan,  1.,  2.,  5.,  6.,  3.,  4.,  0., 12., 10.,  7., 20.,  9.,
       15., 14.,  8., 40., 13., 18., 11., 60., 76., 30., 24., 16., 27.,
       70., 36., 22., 50., 17., 23., 75., 52., 48., 25., 59., 21., 45.,
       46., 35., 32., 42., 63., 73., 28., 19., 29., 64.])

In [90]:
brfss_df_selected['ACEDEPRS'] = brfss_df_selected['ACEDEPRS'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDEPRS != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDEPRS != 9]
brfss_df_selected.ACEDEPRS.unique()

array([nan,  0.,  1.])

In [91]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.BIRTHSEX != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.BIRTHSEX != 7]
brfss_df_selected.BIRTHSEX.unique()

array([nan,  1.,  2.])

In [92]:
# brfss_df_selected['SOMALE'] = brfss_df_selected['SOMALE'].replace({1:0, 2:1, 3:2, 4:3})
# brfss_df_selected = brfss_df_selected[brfss_df_selected.SOMALE != 7]
# brfss_df_selected = brfss_df_selected[brfss_df_selected.SOMALE != 9]
# brfss_df_selected.SOMALE.unique()

In [93]:
brfss_df_selected['SOFEMALE'] = brfss_df_selected['SOFEMALE'].replace({2:0, 3:2})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SOFEMALE != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SOFEMALE != 9]
brfss_df_selected.SOFEMALE.unique()

array([ 0., nan,  1.,  4.,  2.])

In [94]:
brfss_df_selected['TRNSGNDR'] = brfss_df_selected['TRNSGNDR'].replace({4:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.TRNSGNDR != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.TRNSGNDR != 9]
brfss_df_selected.TRNSGNDR.unique()

array([ 0.,  3.,  2.,  1., nan])

In [95]:
brfss_df_selected['ACEDRINK'] = brfss_df_selected['ACEDRINK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDRINK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDRINK != 9]
brfss_df_selected.ACEDRINK.unique()

array([nan,  0.,  1.])

In [96]:
brfss_df_selected['ACEDRUGS'] = brfss_df_selected['ACEDRUGS'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDRUGS != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDRUGS != 9]
brfss_df_selected.ACEDRUGS.unique()

array([nan,  0.,  1.])

In [97]:
brfss_df_selected['ACEDIVRC'] = brfss_df_selected['ACEDIVRC'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDIVRC != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDIVRC != 8]
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDIVRC != 9]
brfss_df_selected.ACEDIVRC.unique()

array([nan,  0.,  1.])

In [98]:
brfss_df_selected['_HLTHPL1'] = brfss_df_selected['_HLTHPL1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPL1 != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPL1 != 7]
brfss_df_selected._HLTHPL1.unique()

array([1., 0.])

In [99]:
brfss_df_selected.shape

(322749, 33)

In [100]:
brfss_df_selected.head()


LSATISFY  EMTSUPRT  SDLONELY  SDHEMPLY  FOODSTMP  SDHFOOD1  SDHBILLS  \
2       2.0       4.0       3.0       2.0       2.0       5.0       1.0   
4       2.0       2.0       2.0       2.0       2.0       4.0       2.0   
5       2.0       2.0       3.0       2.0       2.0       5.0       2.0   
6       2.0       1.0       4.0       2.0       2.0       5.0       2.0   
8       2.0       1.0       3.0       2.0       2.0       5.0       2.0   

   SDHUTILS  SDHTRNSP  SDHSTRE1  DIABETE4  MARITAL  EDUCA  RENTHOM1  CPDEMO1C  \
2       1.0       1.0       3.0       0.0      3.0    4.0       2.0       8.0   
4       2.0       2.0       2.0       2.0      3.0    5.0       1.0       3.0   
5       2.0       2.0       3.0       0.0      3.0    5.0       1.0       1.0   
6       2.0       2.0       5.0       0.0      3.0    4.0       1.0       2.0   
8       2.0       2.0       4.0       0.0      3.0    5.0       1.0       1.0   

   VETERAN3  EMPLOY1  CHILDREN  INCOME3  PREGNANT  SMOKE100  AVEDRNK3  \
2       2.0      7.0       0.0      2.0       NaN       1.0       NaN   
4       2.0      8.0       0.0      7.0       NaN       0.0       1.0   
5       1.0      7.0       0.0      7.0       NaN       0.0       2.0   
6       1.0      8.0       0.0      6.0       NaN       1.0       NaN   
8       2.0      7.0       0.0      6.0       NaN       0.0       NaN   

   USENOW3  ACEDEPRS  BIRTHSEX  SOFEMALE  TRNSGNDR  ACEDRINK  ACEDRUGS  \
2      0.0       NaN       NaN       0.0       0.0       NaN       NaN   
4      2.0       NaN       NaN       0.0       0.0       NaN       NaN   
5      0.0       NaN       NaN       0.0       0.0       NaN       NaN   
6      0.0       NaN       NaN       NaN       0.0       NaN       NaN   
8      0.0       NaN       NaN       0.0       0.0       NaN       NaN   

   ACEDIVRC  QSTLANG  _URBSTAT  _HLTHPL1  
2       NaN      1.0       1.0       1.0  
4       NaN      1.0       1.0       1.0  
5       NaN      1.0       1.0       1.0  
6       NaN      1.0       1.0       1.0  
8       NaN      1.0       1.0       1.0

In [101]:
brfss_df_selected.groupby(['DIABETE4']).size()

DIABETE4
0.0    271013
1.0      7625
2.0     44111
dtype: int64

In [102]:
# 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1',
# 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1',
brfss = brfss_df_selected.rename(columns = {'LSATISFY':'Life Satisfaction', 'EMTSUPRT':'Emotional Support',
                                            'SDLONELY':'Loneliness', 'SDHEMPLY':'Employment',
                                            'FOODSTMP':'Food Stamps', 'SDHFOOD1':'Food Insecurity',
                                            'SDHBILLS':'Bill Insecurity', 'SDHUTILS':'Utility Insecurity',
                                            'SDHTRNSP':'Transportation Insecurity', 'SDHSTRE1':'Stress',
                                            'DIABETE4':'Diabetes', 'MARITAL': 'Marital Status',
                                            'EDUCA':'Education Level', 'RENTHOM1':'Own or Rent Home',
                                            'CPDEMO1C':'Has Phone', 'SMOKE100':'Smoker', 'VETERAN3':'Veteran',
                                            'EMPLOY1':'Employment Status', 'CHILDREN':'Children',
                                            'INCOME3':'Household Income', 'PREGNANT':"Pregnant",
                                            'AVEDRNK3':'Alcohol Consumption', 'HLTHPLN1':'HealthCare',
                                            'ACEDEPRS':'Depressed', 'BIRTHSEX':'Sex',
                                            'SOMALE':'Male Sexual Orientation', 'SOFEMALE':'Female Sexual Orientation',
                                            'TRNSGNDR':'Transgender', 'ACEDRINK':'DrunkFamily',
                                            'ACEDRUGS':'DrugsInFamily', 'ACEDIVRC':'Divorced Parents',
                                            'QSTLANG':'Primary Language', '_URBSTAT':'Urban or Rural',
                                            'USENOW3':'Drug Use',})

In [103]:
brfss.head()

Life Satisfaction  Emotional Support  Loneliness  Employment  Food Stamps  \
2                2.0                4.0         3.0         2.0          2.0   
4                2.0                2.0         2.0         2.0          2.0   
5                2.0                2.0         3.0         2.0          2.0   
6                2.0                1.0         4.0         2.0          2.0   
8                2.0                1.0         3.0         2.0          2.0   

   Food Insecurity  Bill Insecurity  Utility Insecurity  \
2              5.0              1.0                 1.0   
4              4.0              2.0                 2.0   
5              5.0              2.0                 2.0   
6              5.0              2.0                 2.0   
8              5.0              2.0                 2.0   

   Transportation Insecurity  Stress  Diabetes  Marital Status  \
2                        1.0     3.0       0.0             3.0   
4                        2.0     2.0       2.0             3.0   
5                        2.0     3.0       0.0             3.0   
6                        2.0     5.0       0.0             3.0   
8                        2.0     4.0       0.0             3.0   

   Education Level  Own or Rent Home  Has Phone  Veteran  Employment Status  \
2              4.0               2.0        8.0      2.0                7.0   
4              5.0               1.0        3.0      2.0                8.0   
5              5.0               1.0        1.0      1.0                7.0   
6              4.0               1.0        2.0      1.0                8.0   
8              5.0               1.0        1.0      2.0                7.0   

   Children  Household Income  Pregnant  Smoker  Alcohol Consumption  \
2       0.0               2.0       NaN     1.0                  NaN   
4       0.0               7.0       NaN     0.0                  1.0   
5       0.0               7.0       NaN     0.0                  2.0   
6       0.0               6.0       NaN     1.0                  NaN   
8       0.0               6.0       NaN     0.0                  NaN   

   Drug Use  Depressed  Sex  Female Sexual Orientation  Transgender  \
2       0.0        NaN  NaN                        0.0          0.0   
4       2.0        NaN  NaN                        0.0          0.0   
5       0.0        NaN  NaN                        0.0          0.0   
6       0.0        NaN  NaN                        NaN          0.0   
8       0.0        NaN  NaN                        0.0          0.0   

   DrunkFamily  DrugsInFamily  Divorced Parents  Primary Language  \
2          NaN            NaN               NaN               1.0   
4          NaN            NaN               NaN               1.0   
5          NaN            NaN               NaN               1.0   
6          NaN            NaN               NaN               1.0   
8          NaN            NaN               NaN               1.0   

   Urban or Rural  _HLTHPL1  
2             1.0       1.0  
4             1.0       1.0  
5             1.0       1.0  
6             1.0       1.0  
8             1.0       1.0

In [104]:
brfss.shape

(322749, 33)

In [105]:
#Check how many respondents have no diabetes, prediabetes or diabetes. Note the class imbalance!
brfss.groupby(['Diabetes']).size()

Diabetes
0.0    271013
1.0      7625
2.0     44111
dtype: int64

In [106]:
import pandas as pd

# Assuming 'brfss' is your DataFrame
brfss.to_csv('cleanData.csv', encoding='utf-8-sig', index=False)

print("File saved as 'cleanData.csv' in the current working directory.")

File saved as 'cleanData.csv' in the current working directory.


In [107]:
# #Copy old table to new one.
# brfss_binary = brfss
# #Change the column name to Diabetes_binary
# brfss_binary = brfss_binary.rename(columns = {'Diabetes': 'Diabetes_binary'})
# brfss_binary.Diabetes_binary.unique()

In [108]:
# brfss_binary.head()


In [109]:
# brfss_binary.groupby(['Diabetes_binary']).size()

In [110]:
# import numpy as np
# import pandas as pd

# # Separate the 0 (No Diabetes), 1 (Pre-diabetes), and 2 (Diabetes)
# is2 = brfss_binary['Diabetes_binary'] == 2
# brfss_5050_2 = brfss_binary[is2]

# is1 = brfss_binary['Diabetes_binary'] == 1
# brfss_5050_1 = brfss_binary[is1]

# is0 = brfss_binary['Diabetes_binary'] == 0
# brfss_5050_0 = brfss_binary[is0]

# # Select 39977 random cases from the 0 (non-diabetes group)
# brfss_5050_0_rand1 = brfss_5050_0.sample(n=46479, random_state=42)

# # Combine the randomly selected 0s and the 1s
# brfss_5050 = pd.concat([brfss_5050_0_rand1, brfss_5050_1], ignore_index=True)

# # Optional: Verify the shape or composition
# print(brfss_5050.shape)

In [111]:
#Check that it worked. Now we have a dataset of 79,954 rows that is equally balanced with 50% 1 and 50% 0 for the target variable Diabetes_binary
# brfss_5050.head()

In [112]:
# brfss_5050.tail()

In [113]:
# brfss_5050.groupby(['Diabetes_binary']).size()


In [114]:
# print(f'brfss_5050={brfss_5050.shape}',f'brfss_binary={brfss_binary.shape}')


In [115]:
# from google.colab import files
# brfss.to_csv('binaryData.csv', encoding = 'utf-8-sig') 
# files.download('binaryData.csv')